### PR TITLE
installation of plugins

### PR DESCRIPTION
**Pull request by bgruening**
@marie59 this works for me in general. We are just unlucky that it does NOT work for your plugin. Your plugin seems to want to write under /root for unknown reasons.

But please try this procedure with other plugins.

### CODE REVIEW

**Comment by Marie59** [comment]
Yes I think this is fine ! do you think we could also keep the less nice way to add trends earth for now ?

**Comment by bgruening** [comment]
The less nice way does not add the trends.earth - it that a correct understanding? It just downloads the zip file, but the user need to manually select the zip file etc ... but installing the extension manually is easier by using the extension manager and not using a zip file?

**Comment by Marie59** [comment]
> The less nice way does not add the trends.earth - it that a correct understanding? It just downloads the zip file, but the user need to manually select the zip file etc ... but installing the extension manually is easier by using the extension manager and not using a zip file?

Yes it just downloads the zip (which i need to change the path maybe ?) and the the user install it. Yes totally it's way easier how you do it  with the extension manager.
For trends earth for while I don't find another way I will need to do a really clear tuto

**Comment by bgruening** [comment]
What I mean is. Why do you need to zip file in the GUI you can go to the extension (or was it plugins?) and install it via the GUI. No need for a zip file.

**Comment by Marie59** [comment]
> What I mean is. Why do you need to zip file in the GUI you can go to the extension (or was it plugins?) and install it via the GUI. No need for a zip file.

Not for trends.earth for any other 'normal' plugin yes it should work with the GUI by going on plugins (I think extension is the french version name).

**Comment by Marie59** [comment]
For trends if you use the zip from a previous version the installation from the zip works. But if you use the GUI plugins installation it does not work and I think it's because the version is more recent and does something not accepted by or QGIS while installing. It might not be the only plugin with this kind of problem I will try investigate more on that.

**Comment by bgruening** [comment]
There is something wrong with this plugin. Do you know the authors? It also the only plugin I can not install via the other mechanism.

**Comment by bgruening** [comment]
@Marie59 tests are running here now.

**Comment by bgruening** [comment]
have you tested this locally?

**Comment by Marie59** [comment]
> have you tested this locally?

Yes the plugin is installing well locally I still need to test it with some proper files but I checked and It seems I have access to the trends.earth functionalities.

**Pull request merged**
