### PR TITLE
Update QGIS in Galaxy to 3.32

### PR DESCRIPTION
**Pull request by MarkusKonk**

### CODE REVIEW

**Comment by bgruening** [comment]
Thanks!

**Comment by bgruening** [comment]
@MarkusKonk when this https://github.com/usegalaxy-eu/docker-qgis/actions/runs/6667433190 is ready, you should have a new Docker container. I would appreciate if you could test this container manually, without Galaxy, and let me know if it works and if all plugins are still available.

ping also @Marie59

**Comment by Marie59** [comment]
@MarkusKonk Really nice ! Thank you !
I just launched the tool on my local galaxy and it seems to be working (I installed 2 random plugins and it worked).

**Comment by bgruening** [comment]
Cool, then I'm happy to accept a PR to update the tool :)

**Comment by Marie59** [comment]
Should I do it ?

**Comment by bgruening** [comment]
I don't mind :)

**Comment by MarkusKonk** [comment]
great, thanks for testing and deploying!

**Comment by bgruening** [comment]
It should be deployed now.

**Comment by MarkusKonk** [comment]
Just tried it. It's there :).

**Pull request merged**
